### ISSUE TITLE
The redundant fork

### ISSUE THREAD

**Issue by KalessinD** [robrwo/Linux-Statm-Tiny#12]
Hi!

Currently you have a system call of external program `getconf`.
In case of multi-threading it isn't prefereable.

Please replace this call
```perl
`getconf PAGE_SIZE`
```
with the following one POSIX method
```perl
POSIX::sysconf(POSIX::_SC_PAGESIZE);
```

Thanks in advance.

**Comment by JRaspass** [comment]
They seem to give very different results on my Linux (5.16.8; Arch Linux):

```
$ getconf PAGE_SIZE
4096
```
```
$ perl -MPOSIX -E 'say POSIX::_SC_PAGESIZE'
30
```

**Comment by robrwo** [comment]
Same on my Ubuntu Linux

**Comment by JRaspass** [comment]
I forgot the `sysconf`, seems to work now.
