### ISSUE TITLE
should be using namespace::autoclean

### ISSUE THREAD

**Issue by karenetheridge** [robrwo/Linux-Statm-Tiny#8]
namespace::sweep is now obsolete and namespace::autoclean handles more cases, more properly. Anything using Moose, Moo or Mouse should absolutely be using namespace::autoclean; for a few situations (e.g. exporter classes) namespace::clean might be preferable, but a ticket reporting the issue would still be very much welcomed.

see https://rt.cpan.org/Ticket/Display.html?id=101222

**Comment by robrwo** [comment]
What minimum version of namespace::autoclean should I use? 0.24?

**Comment by pdcawley** [comment]
According to the Moo docs, 0.16 is the minimum it plays nicely with.

**Comment by karenetheridge** [comment]
Correct, 0.16 is the version that dropped the loading of Class::MOP to introspect Moo classes.

**Comment by robrwo** [comment]
Fixed in 0.0504
